### ISSUE TITLE
functional test flake: sync_flag not found

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#1066]
I see this flake every now and then locally when running the functional tests - 

```
tests/functional/test_login_from_offline.py::test_login_from_offline PASSED                           [100%]
tests/functional/test_login_from_offline.py::test_login_from_offline ERROR [100%]

==================================== ERRORS ====================================
_________________ ERROR at teardown of test_login_from_offline _________________
TEARDOWN ERROR: Exceptions caught in Qt event loop:
________________________________________________________________________________
Traceback (most recent call last):
  File "/Users/redshiftzero/Documents/Github/securedrop-client/securedrop_client/logic.py", line 478, in on_sync_success
    with open(self.last_sync_filepath, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/gv/2r10zvfj303fyd5_6yn_p0b80000gn/T/tmppyn_ni_7/sync_flag'
________________________________________________________________________________

----------------------------- Captured stderr call -----------------------------
gpg: keybox '/var/folders/gv/2r10zvfj303fyd5_6yn_p0b80000gn/T/tmppyn_ni_7/gpg/pubring.kbx' created
gpg: /var/folders/gv/2r10zvfj303fyd5_6yn_p0b80000gn/T/tmppyn_ni_7/gpg/trustdb.gpg: trustdb created
gpg: key CC40EF1228271441: public key "SecureDrop Test/Development (DO NOT USE IN PRODUCTION)" imported
gpg: key CC40EF1228271441: secret key imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg:       secret keys read: 1
gpg:   secret keys imported: 1
===Flaky Test Report===

test_login_from_offline passed 1 out of the required 1 times. Success!

===End Flaky Test Report===
========================== 1 passed, 1 error in 4.82s ==========================
Exceptions caught in Qt event loop:
________________________________________________________________________________
Traceback (most recent call last):
  File "/Users/redshiftzero/Documents/Github/securedrop-client/securedrop_client/logic.py", line 478, in on_sync_success
    with open(self.last_sync_filepath, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/gv/2r10zvfj303fyd5_6yn_p0b80000gn/T/tmppyn_ni_7/sync_flag'
________________________________________________________________________________
make: *** [test-functional] Error 1
```

**Comment by zenmonkeykstop** [comment]
Closing, no longer observed.
