### ISSUE TITLE
Client crashes if there are failed replies in local db from a previous run of the 0.2.1 client

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#1185]
## STR

1. Checkout the 0.2.1 client (https://github.com/freedomofpress/securedrop-client/releases/tag/0.2.1) 
2. `pip install --require-hashes -r requirements/dev-requirements.txt`
3. Send some failed replies
   - `wget https://gist.githubusercontent.com/creviera/5ba70d50c12b6a6df6f98ed40ad09645/raw/5caef3339ceab1fc997ccb6b9e337bc8828ef12f/failed-reply`
   - `git apply failed-reply`
   - Run the client and send some replies that will fail
4. Now checkout `main` branch
5. `pip install --require-hashes -r requirements/dev-requirements.txt`
6. Run the client, view a source with a failed reply, and wait until the first sync finishes

## Expected

Failed replies should have the initials of the journalist in the badges, and the client should not crash.

## Actual

Failed replies are missing the initials of the journalist in the badges, and the client crashes after a sync.

**Comment by conorsch** [comment]
Sharing the stack trace I see locally when reproducing. 

<details>
<summary>
exception output
</summary>

```
Traceback (most recent call last):
  File "/home/user/.virtualenvs/sdc/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1641, in refresh
    state = attributes.instance_state(instance)
AttributeError: 'NoneType' object has no attribute '_sa_instance_state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/securedrop-client/securedrop_client/logic.py", line 563, in on_sync_success
    self.gui.refresh_current_source_conversation()
  File "/home/user/securedrop-client/securedrop_client/gui/main.py", line 149, in refresh_current_source_conversation
    self.main_view.on_source_changed()
  File "/home/user/securedrop-client/securedrop_client/gui/widgets.py", line 651, in on_source_changed
    conversation_wrapper.conversation_view.update_conversation(source.collection)
  File "/home/user/securedrop-client/securedrop_client/gui/widgets.py", line 2960, in update_conversation
    self.controller.session.refresh(conversation_item.journalist)
  File "/home/user/.virtualenvs/sdc/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1643, in refresh
    raise exc.UnmappedInstanceError(instance)
sqlalchemy.orm.exc.UnmappedInstanceError: Class 'builtins.NoneType' is not mapped
```
</details>
