### ISSUE TITLE
Downloading a file after deleting a conversation fails

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#1450]
## STR

Surfaced in #1447

1. Download one or more files from several source and see that the feature works
2. Delete a conversation that includes files (it doesn't matter if they've been downloaded or not)
3. Now try to download one or more files from a source

## Expected

For a single file or multiple files to successfully download after another source conversation has been deleted.

## Actual

The pending download animation is in the `DOWNLOADING` pending state next to each file until you close the client, even after the error message appears about the failed download.

## Additional info

1. Looks like this started breaking in commit https://github.com/freedomofpress/securedrop-client/commit/1b68a9cdb238473d4aa7ce8f93a5f2bd89bb9733 - @gonzalo-bulnes, if you have time, would you mind taking a look into this, and keep @rocodes in the loop on progress (ro is currently busy working on another high-priority bug fix, which is why I was hoping to pull you in gonzalo)?
2. The error log says:

```
2022-03-21 18:13:32,091 - securedrop_client.storage:204(chronometer) INFO: update_sources duration: 5.0167s
2022-03-21 18:13:32,093 - securedrop_client.logic:660(on_sync_failure) WARNING: sync failure: (sqlite3.OperationalError) database is locked
[SQL: UPDATE sources SET last_updated=? WHERE sources.id = ?]
[parameters: (('2022-03-22 01:00:00.681624', 19), ('2022-03-22 01:00:01.863806', 20), ('2022-03-22 01:00:03.655576', 21))]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by gonzalo-bulnes** [comment]
Yes @creviera, happy to look into this 👍
@rocodes how do you want to do this? I'll start by looking at the commit @creviera identified and report my findings here 🙂

**Comment by gonzalo-bulnes** [comment]
@creviera Did you `git bisect` to find that commit? (My actual question: how confident are we the issue appeared there, can I skip the confirmation step for a first read-through?)

**Comment by creviera** [comment]
> @creviera Did you `git bisect` to find that commit? (My actual question: how confident are we the issue appeared there, can I skip the confirmation step for a first read-through?)

I think you should confirm it. I just had a suspicion that is was either the recent download all PR or the recent safe delete PR, so I zero'd in on the commit by checking the one prior, which doesn't see the error.

**Comment by gonzalo-bulnes** [comment]
First thoughts:

- fact: the log makes mention of a locked database
- IIRC SQLite3 is file-based and locks the files when writing to them
- note: the SQLAlchemy `OperationalError` doesn't indicate much in itself, it is a generic error.
- fact: what fails is a SQL `UPDATE`
- I think:
  - that seems like what I'd expect for a database lock error: could another write be happening concurrently?
  - that `UPDATE` shouldn't be too hard to locate in the code
  - it is not immediately obvious to me that the update happens in the diff of the suspicious commit
  - the suspicious commit adds a check before a write, I don't think that would cause a lock error because I don't think a read require the database to be locked
  - unless the nested transaction could have sonething to do with it?

**Comment by gonzalo-bulnes** [comment]
@rocodes I assigned us because I think you'll have much better context than me on both SQLite3 transactions behavior and the sync!

**Comment by rocodes** [comment]
Just posting a longer explanation here for clarity: 

Your research on this already is very helpful, Gonzalo! it lines up with what I noticed in the other issue I'm working on (replies out of order).  What I meant is that I don't think this is a downloading-specific issue, and I'd like to get the changes in #1449 in and then see where we're at I know that they will fix some of the database problems. 
 
High-level summary:
The changes in #1432 included some logic to avoid re-downloading deleted conversations with sources (since that was our concern--what if we 'safe delete' a source and then their data is repopulated by a sync with the server that was kicked off before the deletion was scheduled on the server?).  However, these changes were too aggressive (skipping one sync for a single source that has just had safe-delete run on it) and led to database conflicts when the source was also modified locally.
 
The changes in #1449 fix this by [reverting some of the changes to `update_sources`](https://github.com/freedomofpress/securedrop-client/pull/1449/files#diff-2733f413482546949a61df863376e7a3f9565395057ba2443ad9622d53214f1aL279-R299) (among other things), so that most source metadata is still updated normally on a sync, even if the source conversation was just locally deleted.

Once those changes are in place, then investigating any remaining database locking issues will make a lot of sense, because then it will be locking due to concurrency issues, or improper error handling (which relates to [this issue](https://github.com/freedomofpress/securedrop-client/issues/1440) or something.

**Comment by rocodes** [comment]
Update:

This is a more complete stacktrace. A db commit at the end of `update_sources` while the sync is in progress seems to be what's triggering the database lock. This can be reproduced _without_ downloading/deleting a file (it's a bug with #1432, it's not related to downloading files).    

```
2022-03-22 15:27:29,144 - securedrop_client.sync:144(sync) ERROR: Traceback (most recent call last):
  File "/home/user/securedrop-client/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1224, in _execute_context
    cursor, statement, parameters, context
  File "/home/user/securedrop-client/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 549, in do_executemany
    cursor.executemany(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/securedrop-client/securedrop_client/sync.py", line 137, in sync
    self.job._do_call_api(self.api_client, session)
  File "/home/user/securedrop-client/securedrop_client/api_jobs/base.py", line 73, in _do_call_api
    result = self.call_api(api_client, session)
  File "/home/user/securedrop-client/securedrop_client/api_jobs/sync.py", line 47, in call_api
    update_local_storage(session, sources, submissions, replies, self.data_dir)
  File "/home/user/securedrop-client/securedrop_client/storage.py", line 184, in update_local_storage
    remote_sources, get_local_sources(session), skip_conversation_uuids, session, data_dir
  File "/home/user/securedrop-client/securedrop_client/storage.py", line 332, in update_sources
    session.commit()
  File "/home/user/securedrop-client/.venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1026, in commit
    self.transaction.commit()
  File "/home/user/securedrop-client/.venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 493, in commit
    self._prepare_impl()
  File "/home/user/securedrop-client/.venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 472, in _prepare_impl
    self.session.flush()
  File "/home/user/securedrop-client/.venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2451, in flush
    self._flush(objects)
  File "/home/user/securedrop-client/.venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2589, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/user/securedrop-client/.venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/user/securedrop-client/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/home/user/securedrop-client/.venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2549, in _flush
    flush_context.execute()
  File "/home/user/securedrop-client/.venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/user/securedrop-client/.venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/user/securedrop-client/.venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/home/user/securedrop-client/.venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 978, in _emit_update_statements
    statement, multiparams
  File "/home/user/securedrop-client/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/user/securedrop-client/.venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/user/securedrop-client/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/home/user/securedrop-client/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/user/securedrop-client/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/user/securedrop-client/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/user/securedrop-client/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/home/user/securedrop-client/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1224, in _execute_context
    cursor, statement, parameters, context
  File "/home/user/securedrop-client/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 549, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: UPDATE sources SET last_updated=? WHERE sources.id = ?]
[parameters: (('2022-03-17 21:00:08.020099', 1), ('2022-03-17 21:03:31.584632', 2), ('2022-03-21 16:20:20.651299', 3), ('2022-03-22 15:03:17.908940', 4), ('2022-03-22 15:03:46.121036', 5))]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by gonzalo-bulnes** [comment]
Super clear @rocodes, thank for the detailed explanation. I didn't go further than that initial read-through, and it makes complete sense to wait for the ongoing changes to be applied.

Since you're already working on those, can you ping me when you find it useful? I'll read through the stack trace to get a better understanding of the moving pieces in the meantime 🙂

**Comment by rocodes** [comment]
I was _just_ writing to you :upside_down_face: Let's connect whenever it's convenient for you. There are a lot of places where we have some "naked" `session.commit()`s, and depending how our investigation goes we may want to move this conversation to https://github.com/freedomofpress/securedrop-client/issues/1440

**Comment by rocodes** [comment]
Sure, there's no rush (I sent you a message on one of our other comms platforms, long story short is I'm happy to connect in whatever way is easiest/best for you!)--I can bring you up to speed on what I _think_ is happening and we can take it from there

**Comment by gonzalo-bulnes** [comment]
Awesome! Thanks @rocodes. (I wrote down a couple of questions and thoughts in #1449, absolutely non-urgent, just to get my head in motion 😛)
