### ISSUE TITLE
Client crashes when user clicks Download in Offline mode

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-client#146]
In Qubes, the application crashes when a user chooses not to log in, opens a source, and chooses Download for a not previously-downloaded file submission, with error text: 
```
^[Traceback (most recent call last):
  File "/opt/venvs/securedrop-client/lib/python3.5/site-packages/securedrop_client/gui/widgets.py", line 462, in mouseReleaseEvent
    self.controller.on_file_download(self.source, self.submission)
  File "/opt/venvs/securedrop-client/lib/python3.5/site-packages/securedrop_client/logic.py", line 490, in on_file_download
    func = self.api.download_submission
AttributeError: 'NoneType' object has no attribute 'download_submission'
```
(Clicking Open on a previously-downloaded submission works as expected, spawning a dispVM to view the file.)

**Comment by redshiftzero** [comment]
fixed in #150
