### ISSUE TITLE
Error displaying message

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop-client#171]
```
Traceback (most recent call last):
  File "/home/heartsucker/code/freedomofpress/securedrop-client/securedrop_client/gui/main.py", line 154, in on_source_changed
    self.show_conversation_for(self.current_source)
  File "/home/heartsucker/code/freedomofpress/securedrop-client/securedrop_client/gui/main.py", line 185, in show_conversation_for
    "<Reply not yet downloaded>")
  File "/home/heartsucker/code/freedomofpress/securedrop-client/securedrop_client/gui/main.py", line 163, in add_item_content_or
    adder(item.content)
  File "/home/heartsucker/code/freedomofpress/securedrop-client/securedrop_client/models.py", line 33, in content
    return self.data.get(fn_no_ext)
  File "/home/heartsucker/code/freedomofpress/securedrop-client/securedrop_client/data.py", line 17, in get
    msg = fh.read()
  File "/home/heartsucker/.local/share/virtualenvs/securedrop-client-GExBtLKv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd8 in position 0: unexpected end of data
```

**Comment by redshiftzero** [comment]
Did you re-run your container after this change was merged https://github.com/freedomofpress/securedrop/pull/3927 ?

**Comment by redshiftzero** [comment]
(I saw this before here https://github.com/freedomofpress/securedrop-client/pull/114#issuecomment-436496124 )

**Comment by heartsucker** [comment]
Confirmed that the branch we're running against did not have that change added.
