### ISSUE TITLE
Client violates AppArmor profile if there are packages in `/usr/local/lib/python3.9/dist-packages`

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop-client#1836]
## Description

If there are packages in `sd-app:/usr/local/lib/python3.9/dist-packages`, `securedrop-client` will attempt to scan them when it loads `pkg_resources`, which will violate the AppArmor policy in force.

## Steps to Reproduce

On `sd-app`:

```
$ sudo apt install python3-pip
$ sudo pip install poetry  # e.g.
$ securedrop-client
```

## Expected Behavior

The Client runs, self-contained in its virtualenv.

## Actual Behavior

```sh-session
user@sd-app:~$ LOGLEVEL=DEBUG securedrop-client
[...]
Traceback (most recent call last):
  File "/opt/venvs/securedrop-client/./bin/sd-client", line 5, in <module>
    from securedrop_client.app import run
  File "/opt/venvs/securedrop-client/lib/python3.9/site-packages/securedrop_client/app.py", line 40, in <module>
    from securedrop_client.gui.main import Window
  File "/opt/venvs/securedrop-client/lib/python3.9/site-packages/securedrop_client/gui/main.py", line 32, in <module>
    from securedrop_client.gui.auth import LoginDialog
  File "/opt/venvs/securedrop-client/lib/python3.9/site-packages/securedrop_client/gui/auth/__init__.py", line 20, in <module>
    from securedrop_client.gui.auth.dialog import LoginDialog  # noqa: F401
  File "/opt/venvs/securedrop-client/lib/python3.9/site-packages/securedrop_client/gui/auth/dialog.py", line 22, in <module>
    from pkg_resources import resource_string
  File "/opt/venvs/securedrop-client/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/opt/venvs/securedrop-client/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/opt/venvs/securedrop-client/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/venvs/securedrop-client/lib/python3.9/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws = cls()
  File "/opt/venvs/securedrop-client/lib/python3.9/site-packages/pkg_resources/__init__.py", line 567, in __init__
    self.add_entry(entry)
  File "/opt/venvs/securedrop-client/lib/python3.9/site-packages/pkg_resources/__init__.py", line 623, in add_entry
    for dist in find_distributions(entry, True):
  File "/opt/venvs/securedrop-client/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2065, in find_on_path
    for dist in factory(fullpath):
  File "/opt/venvs/securedrop-client/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2127, in distributions_from_metadata
    if len(os.listdir(path)) == 0:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.9/dist-packages/zipp-3.17.0.dist-info'
```

If you delete `/usr/local/lib/python3.9/dist-packages/zipp-3.17.0.dist-info` and try again, the same error will occur with whatever package is now alphabetically last, and so on.

## Comments

There are two ways to think about this:

1. This is a bug, specifically an overzealous AppArmor policy.  The Client *should* be able to scan `/usr/local/lib/python3.9/dist-packages`; it won't actually load anything from there if installed correctly.
2. This is the AppArmor policy working as intended.  Packages in `/usr/local/lib/python3.9/dist-packages` indicate that `sd-app` has been tampered with, benignly or otherwise.

**Comment by legoktm** [comment]
> If there are packages in `sd-app:/usr/local/lib/python3.9/dist-packages`, `securedrop-client` will attempt to scan them when it loads `pkg_resources`, which will violate the AppArmor policy in force.

Would #1672 take care of this? I have the patch ready to go, I just didn't get around to submitting it as a PR.

**Comment by legoktm** [comment]
> There are two ways to think about this:
> <snip>

I think I'm mostly neutral with a small lean to no. 2, that the policy is working fine. There shouldn't be stuff in /usr/local, which means your system python installation is "compromised" (not necessarily maliciously, but it's not in the pristine packaged state) and all bets are off then. In bookworm this becomes impossible:
```
user@debian-test:~$ sudo pip install poetry
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```
which is why I think the answer doesn't really matter in the long run for this specific case.

**Comment by cfm** [comment]
On Wed, Feb 14, 2024 at 05:10:29PM -0800, Kunal Mehta wrote:
> Would #1672 take care of this? I have the patch ready to go, I just
> didn't get around to submitting it as a PR.

I think the question here is:  Will importlib.resources also scan
system-level package directories without being specifically asked to do
so?

**Comment by legoktm** [comment]
> I think the question here is:  Will importlib.resources also scan
system-level package directories without being specifically asked to do
so?

I posted #1851 in which we don't use importlib.resources, just plain single-file loading.
