### ISSUE TITLE
Attempt to delete source in offline mode results in client crash

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#198]
Steps to reproduce:
1) Launch client with locally stored sources
2) Close the "Sign in" window
3) Click "Delete" next to any given source.

Expected behavior:
- Client should show "You must sign in" error that it displays when attempting to star a source in offline mode.

Actual behavior:
- Client shows deletion prompt. If user confirms, client crashes with:

```
Traceback (most recent call last):
  File "/home/erik/Code/securedrop-client/securedrop_client/gui/widgets.py", line 317, in delete_source
    messagebox.launch()
  File "/home/erik/Code/securedrop-client/securedrop_client/gui/widgets.py", line 227, in launch
    self.controller.delete_source(self.source)
  File "/home/erik/Code/securedrop-client/securedrop_client/logic.py", line 610, in delete_source
    self.api.delete_source,
AttributeError: 'NoneType' object has no attribute 'delete_source'
```

**Comment by redshiftzero** [comment]
@ultimatecoder would you like to work on this issue?

**Comment by ultimatecoder** [comment]
@redshiftzero Yes, I will. :blush:
