### ISSUE TITLE
SIGINT not correctly intercepted when modals visible

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop-client#210]
# Steps to reproduce

1. `pipenv run ./run.sh`
2. Wait for login modal to appear
3. `^C` in the terminal

# Expected outcome

App quits

# Actual outcome

App does not quit, but if you hit the escape key in the modal it falls back to the main thread and then bails with:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/heartsucker/code/freedomofpress/securedrop-client/securedrop_client/__main__.py", line 3, in <module>
    run()
  File "/home/heartsucker/code/freedomofpress/securedrop-client/securedrop_client/app.py", line 184, in run
    start_app(args, qt_args)
  File "/home/heartsucker/code/freedomofpress/securedrop-client/securedrop_client/app.py", line 170, in start_app
    client.setup()
  File "/home/heartsucker/code/freedomofpress/securedrop-client/securedrop_client/logic.py", line 134, in setup
    self.gui.show_login()
  File "/home/heartsucker/code/freedomofpress/securedrop-client/securedrop_client/gui/main.py", line 97, in show_login
    self.login_dialog.exec()
KeyboardInterrupt
```

**Comment by eloquence** [comment]
This appears to no longer be an issue with the current login flow. The app does terminate after ^C (though it takes several seconds to do so).
