### ISSUE TITLE
Syncing the API immediately after a source is created will cause a fatal application error

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop-client#219]
The root cause is this issue in SecureDrop core: https://github.com/freedomofpress/securedrop/issues/4005

In short, if a source does not yet have a PGP key created, the function that retrieves the PGP pub key on the server will unexpectedly return all pub keys.

The client error is:

```
Traceback (most recent call last):
  File "/home/heartsucker/code/freedomofpress/securedrop-client/securedrop_client/logic.py", line 189, in <lambda>
    lambda: self.completed_api_call(new_thread_id, callback))
  File "/home/heartsucker/code/freedomofpress/securedrop-client/securedrop_client/logic.py", line 242, in completed_api_call
    user_callback(result_data)
  File "/home/heartsucker/code/freedomofpress/securedrop-client/securedrop_client/logic.py", line 419, in on_synced
    self.gpg.import_key(source.uuid, pub_key)
  File "/home/heartsucker/code/freedomofpress/securedrop-client/securedrop_client/crypto.py", line 116, in import_key
    raise RuntimeError('Expected exactly one fingerprint. Found: {}'
RuntimeError: Expected exactly one fingerprint.
```

**Comment by heartsucker** [comment]
https://github.com/freedomofpress/securedrop/issues/4005 was merged into `develop`, so this can be closed.
