### ISSUE TITLE
File download and open not working

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#266]
# STR

0. start client, log in to server
1. submit file as a source
2. click on source, and double click on a document to download and open

# Expected behavior

Document downloads and decrypts

# Actual behavior

```
Traceback (most recent call last):
  File "/Users/redshiftzero/.virtualenvs/securedrop-client-l0Id-Ywn/lib/python3.5/shutil.py", line 538, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/gv/2r10zvfj303fyd5_6yn_p0b80000gn/T/tmp.dOSXysZF/data/1-mushy_exposure-doc.gz.gpg' -> '/var/folders/gv/2r10zvfj303fyd5_6yn_p0b80000gn/T/tmp.dOSXysZF/data/1-mushy_exposure-doc.gz.gpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/redshiftzero/Documents/Github/securedrop-client/securedrop_client/logic.py", line 225, in <lambda>
    lambda: self.completed_api_call(new_thread_id, callback))
  File "/Users/redshiftzero/Documents/Github/securedrop-client/securedrop_client/logic.py", line 276, in completed_api_call
    user_callback(result_data, current_object=current_object)
  File "/Users/redshiftzero/Documents/Github/securedrop-client/securedrop_client/logic.py", line 622, in on_file_downloaded
    shutil.move(filename, filepath_in_datadir)
  File "/Users/redshiftzero/.virtualenvs/securedrop-client-l0Id-Ywn/lib/python3.5/shutil.py", line 552, in move
    copy_function(src, real_dst)
  File "/Users/redshiftzero/.virtualenvs/securedrop-client-l0Id-Ywn/lib/python3.5/shutil.py", line 251, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/redshiftzero/.virtualenvs/securedrop-client-l0Id-Ywn/lib/python3.5/shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/gv/2r10zvfj303fyd5_6yn_p0b80000gn/T/tmp.dOSXysZF/data/1-mushy_exposure-doc.gz.gpg'
```

# Comment

A fix should include a regression test

**Comment by redshiftzero** [comment]
Hmm so it looks like this is resolved after #231, but the UI `download` icon in the conversation view does not update to `open` after the file download/decrypt completes
