### ISSUE TITLE
Attempting to delete a source throws an exception:

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#297]
## Description

Attempting to delete a source throws an exception. This is currently a bug on `master`.

## Details

```pytb
Traceback (most recent call last):
  File "/home/heartsucker/code/freedomofpress/securedrop-client/securedrop_client/gui/main.py", line 177, in on_source_changed
    self.show_conversation_for(self.current_source, self.controller.is_authenticated)
  File "/home/heartsucker/code/freedomofpress/securedrop-client/securedrop_client/gui/main.py", line 190, in show_conversation_for
    is_authenticated)
  File "/home/heartsucker/code/freedomofpress/securedrop-client/securedrop_client/gui/widgets.py", line 1264, in __init__
    parent=self)
  File "/home/heartsucker/code/freedomofpress/securedrop-client/securedrop_client/gui/widgets.py", line 1170, in __init__
    self.update_conversation(self.source.collection)
  File "/home/heartsucker/code/freedomofpress/securedrop-client/securedrop_client/gui/widgets.py", line 1184, in update_conversation
    self.add_message(conversation_item)
  File "/home/heartsucker/code/freedomofpress/securedrop-client/securedrop_client/gui/widgets.py", line 1218, in add_message
    self.controller.session.refresh(message)
  File "/home/heartsucker/.local/share/virtualenvs/securedrop-client-GExBtLKv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 1498, in refresh
    self._expire_state(state, attribute_names)
  File "/home/heartsucker/.local/share/virtualenvs/securedrop-client-GExBtLKv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 1600, in _expire_state
    self._validate_persistent(state)
  File "/home/heartsucker/.local/share/virtualenvs/securedrop-client-GExBtLKv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2047, in _validate_persistent
    state_str(state))
sqlalchemy.exc.InvalidRequestError: Instance '<Message at 0x7f2f28029eb8>' is not persistent within this Session
```

## STR

Either try to delete Source from the Source dropdown menu in the upper-right corner of the client or via the 'x' icon next to the Source codename in the Source list.

This may be related to what I suggested in #296.

**Comment by creviera** [comment]
Just realized this isn't a current bug in `master` so closing

**Comment by creviera** [comment]
This is happening on `master` branch so will be working on fixing this regression separate from this PR: https://github.com/freedomofpress/securedrop-client/pull/293

**Comment by creviera** [comment]
#### More info

After digging in, I found that this used to work a couple weeks ago when there was a fix for deleting a source here: https://github.com/freedomofpress/securedrop-client/pull/281. 

It stopped working after the PR that followed it: https://github.com/freedomofpress/securedrop-client/pull/277 (looks like the changes had to do with database changes)

@heartsucker do you think it's still related to #296?

**Comment by creviera** [comment]
To fix this we can implement the fix that was proposed here: https://github.com/freedomofpress/securedrop-client/issues/195 where no source should be selected after the currently-selected source is deleted.
