### ISSUE TITLE
TypeError when username missing in Login

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#449]
## Description

When the uesrname is missing and the user clicks "Sign In" the application crashes with this backtrace:

```
Traceback (most recent call last):
  File "freedomofpress/securedrop-client/securedrop_client/gui/widgets.py", line 1280, in validate
    self.controller.login(username, password, tfa_token)
  File "freedomofpress/securedrop-client/securedrop_client/logic.py", line 284, in login
    password, totp, self.proxy)
TypeError: __init__() missing 1 required positional argument: 'totp'
```

**Comment by creviera** [comment]
Closing because this is no longer an issue.

_it never was an issue except on my machine_
