### ISSUE TITLE
Segfault when exporting - FileNotFoundError

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-client#641]
Initially reported in https://github.com/freedomofpress/securedrop-client/pull/631#issuecomment-561698081 

I was unable to reproduce the issue again, but opening an issue to track in case someone can reproduce. 
When running export in rapid succession, an error occurred as the export was being performed:
```
Traceback (most recent call last):
  File "/opt/venvs/securedrop-client/lib/python3.7/site-packages/securedrop_client/export.py", line 300, in print
    self._run_print(temp_dir, filepaths)
  File "/opt/venvs/securedrop-client/lib/python3.7/site-packages/securedrop_client/export.py", line 244, in _run_print
    archive_path = self._create_archive(archive_dir, self.PRINT_FN, metadata, filepaths)
  File "/opt/venvs/securedrop-client/lib/python3.7/site-packages/securedrop_client/export.py", line 151, in _create_archive
    cls._add_file_to_archive(archive, filepath)
  File "/opt/venvs/securedrop-client/lib/python3.7/site-packages/securedrop_client/export.py", line 184, in _add_file_to_archive
    archive.add(filepath, arcname=arcname, recursive=False)
  File "/opt/venvs/securedrop-client/lib/python3.7/tarfile.py", line 1928, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "/opt/venvs/securedrop-client/lib/python3.7/tarfile.py", line 1807, in gettarinfo
    statres = os.lstat(name)
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.securedrop_client/data/Secret_Docs.docx'

QObject::~QObject: Timers cannot be stopped from another thread
Segmentation fault
```

It's unclear if it was limited to testing-only (thus unlikely to happen in prod or prod-like scenarios) as I had manually introduced a syntax error in the export script.

**Comment by creviera** [comment]
Ah, yes, this was fixed as part of that PR that you commented on, I just forgot to verify it. Thank you for reporting, this commit fixed the issue: https://github.com/freedomofpress/securedrop-client/pull/631/commits/cc76d1e752eb35889ccccf8561bdda8975e5a4a2

Note: We'll have to make sure we don't reintroduce this when this is worked on: https://github.com/freedomofpress/securedrop-client/pull/631/commits/cc76d1e752eb35889ccccf8561bdda8975e5a4a2
