### ISSUE TITLE
snippet updates can crash the app

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#880]
I triggered this when adding 100 sources to try out #870, I think it's a rare race but regardless we should understand how this can happen as there are a class of related bugs like this (where the C++ object is deleted and the Python wrapper is not).

# STR 

[ Removed STR because they weren't reliable ]

# Expected Behavior

Application does not crash

# Actual Behavior

As the sync is running, the source list will get repopulated with new SourceWidgets. Then, the following happens when the snippet tries to update after a relevant message/reply download finishes:

```
Traceback (most recent call last):
  File "/Users/redshiftzero/Documents/Github/securedrop-client/securedrop_client/gui/widgets.py", line 900, in set_snippet
    if source_widget:
  File "/Users/redshiftzero/Documents/Github/securedrop-client/securedrop_client/gui/widgets.py", line 1073, in set_snippet
    msg_text = msg_text[:120] + "..."
  File "/Users/redshiftzero/Documents/Github/securedrop-client/securedrop_client/gui/__init__.py", line 175, in setText
    self.setTextFormat(Qt.PlainText)
RuntimeError: wrapped C/C++ object of type SecureQLabel has been deleted
```

**Comment by redshiftzero** [comment]
I suspect the same underlying issue could be causing all the similar crasher scenarios (cross-linking also #857 #859):

1. UI is drawn
2. an Action starts happening in the background (file is downloading). It takes a while.
3. due to a number of potential reasons (e.g. the db object itself was deleted, a widget in the part of the UI that receives a signal when the action is completed), the underlying widget is gone
4. we see: `RuntimeError: wrapped C/C++ object of type <relevant widget> has been deleted` - i.e. the python object has not been garbage collected but the corresponding C++ object is deleted

We must be doing something like keeping references to Python wrappers that have their corresponding C++ objects deleted.. or we need to explicitly disconnect signal/slot connections when we delete widgets to prevent crashes.

**Comment by creviera** [comment]
ill try to repro

**Comment by creviera** [comment]
> 3. Start the server, and wait for the messages to update.

Does it matter if you select a source? Should it crash immediately?

**Comment by creviera** [comment]
Update: I didn't see the application crash

**Comment by redshiftzero** [comment]
This is really hard to reproduce, but the problem (one will need to inspect the logic to agree with me here) is that we are keeping a reference to the `SourceWidget` pyqt Python wrapper in a dict on `SourceList` even when the source has been deleted, this can cause a crash:

```
(Pdb) type(self)
<class 'securedrop_client.gui.widgets.SourceList'>
(Pdb) self.source_widgets['7851ffd2-6d9e-4709-85ae-0ea7b63625e5'].preview.setText('beep boop')
*** RuntimeError: wrapped C/C++ object of type SecureQLabel has been deleted
```

I debugged this by putting a breakpoint in here:

```diff
diff --git a/securedrop_client/gui/widgets.py b/securedrop_client/gui/widgets.py
index b6fb937..75eb0ab 100644
--- a/securedrop_client/gui/widgets.py
+++ b/securedrop_client/gui/widgets.py
@@ -876,6 +876,8 @@ class SourceList(QListWidget):
         message, then update the source's preview snippet to the referenced
         content.
         """
+        from PyQt5.QtCore import pyqtRemoveInputHook; pyqtRemoveInputHook()
+        import pdb; pdb.set_trace()
         source_widget = self.source_widgets.get(source_uuid)
         if source_widget:
             source_widget.set_snippet(source_uuid, message_uuid, content)
```

And then deleting sources to see if I could trigger the same RuntimeError on any of the wrappers when updating the snippet text, which one can.

**Comment by creviera** [comment]
I will give this a try. Just wanted to mention that I was also thinking that was the issue with https://github.com/freedomofpress/securedrop-client/issues/859#issuecomment-594996358 and am working on testing this theory since I am sometimes (1/10 tries maybe) able repro the issue. I'm working on building confidence as well in this theory.

**Comment by redshiftzero** [comment]
oh snap, I hadn't seen that, thanks - yep I agree, this is a very closely related issue. We should do a scan through all the places that we are using these dicts in the GUI code to ensure that deleted objects will not have lingering references to their Python wrappers. Then I think we'll be in much better shape. I'll handle the SourceList.source_widgets dict for this issue.
